server:
  port: 8080
spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sensordb
    username: postgres
    password: postgres
    postgres:
      url: jdbc:postgresql://localhost:5432/sensordb
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    url: jdbc:postgresql://localhost:5432/sensordb   # optional, defaults to datasource
    user: postgres
    password: postgres
    schemas: public
    locations: classpath:db/migration
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false
    debug: true


  kafka:
    client-id: warehouse-service
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
        batch.size: 32768
        # Json
        spring.json.add.type.headers: true
        spring.json.write_dates_as_timestamps: false
    consumer:
      group-id: ${KAFKA_GROUP:warehouse-service}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
      max-poll-records: 500

      listener:
          ack-mode: record
          concurrency: 3

      admin:
          fail-fast: true



app:
  kafka:
    topics:
      measurements:
        events: sensor

  udp:
    listeners:
      # Listener 1: Temperature Sensor
      #echo "25.8" | nc.exe -u -w1 127.0.0.1 3344
      #echo "61.3" | nc.exe -u -w1 127.0.0.1 3355
      - port: 3344
        type: TEMPERATURE
        bind-host: 127.0.0.1
      - port: 3355
        type: HUMIDITY
        # Specific host for this port (e.g., dedicated sensor network IP)
        bind-host: 127.0.0.1

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    opentelemetry:
      export:
        schedule-delay: 1s       # batch flush interval      # 1.0 = sample all (turn down in prod)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: warehouse-service
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always



  prometheus:
    metrics:
      export:
        enabled: true


logging:
  pattern:
    level: "%5p [${spring.application.name:-},trace=%X{traceId:-},span=%X{spanId:-}]"
  level:
    org.hibernate.SQL: INFO